CFLAGS = -W -pedantic -ansi -g 
UDPtimed: UDPtimed.c
	${CC} -o $@ ${CFLAGS} UDPtimed.c errexit.c

UDPtime: UDPtime.c
	${CC} -o $@ ${CFLAGS} UDPtime.c errexit.c

TCPecho: TCPecho.c
	${CC} -o $@ ${CFLAGS} TCPecho.c errexit.c

TCPechod: TCPechod.c
	${CC} -o $@ ${CFLAGS} TCPechod.c errexit.c

tcpclient: tcpclient.c
	${CC} -o $@ ${CFLAGS} tcpclient.c errexit.c

tcpserver: tcpserver.c
	${CC} -o $@ ${CFLAGS} tcpserver.c errexit.c

udpclient: udpclient.c
	${CC} -o $@ ${CFLAGS} udpclient.c errexit.c

udpserver: udpserver.c
	${CC} -o $@ ${CFLAGS} udpserver.c errexit.c

tcpclientQ4: tcpclient_Q4.c
	${CC} -o $@ ${CFLAGS} tcpclient_Q4.c errexit.c

udpclientQ4: udpclient_Q4.c
	${CC} -o $@ ${CFLAGS} udpclient_Q4.c errexit.c